# Generated by Django 5.1.3 on 2024-11-16 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_usuarios', '0002_alter_customuser_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bicicleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('eletrica', 'Elétrica'), ('passeio', 'Passeio'), ('urbana', 'Urbana')], max_length=10)),
                ('status', models.BooleanField(default=True)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
