# Generated by Django 5.1.3 on 2024-11-17 12:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_usuarios', '0003_bicicleta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluguel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_bicicleta', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=6, unique=True)),
                ('inicio_aluguel', models.DateTimeField(default=django.utils.timezone.now)),
                ('fim_aluguel', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
