# Generated by Django 5.1.3 on 2024-11-17 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_usuarios', '0004_aluguel'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluguel',
            name='devolvida',
            field=models.BooleanField(default=False),
        ),
    ]
