# Generated by Django 5.1.3 on 2024-11-17 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_usuarios', '0006_alter_aluguel_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluguel',
            name='tempo_total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
